# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sentiment' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sentiment
  pod 'MobileCenter/Push', '~> 0.13.0'
  pod 'MobileCenter/Crashes', '~> 0.13.0'
  pod 'MobileCenter/Analytics', '~> 0.13.0'
  pod 'RNMobileCenterShared', '~> 0.10.0'

  

  target 'SentimentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Sentiment-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sentiment-tvOS

  target 'Sentiment-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
